name: sss_computing_client
description: "Client application for the SSS-Computing project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.0.1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hmi_core:
    git:
      url: https://github.com/a-givertzman/hmi_core.git
      ref: 2.1.1
  hmi_widgets:
    git:
      url: https://github.com/a-givertzman/hmi_widgets.git
      ref: 1.0.2
  ext_rw:
    git:
      url: https://github.com/a-givertzman/dart_ext_rw.git
      ref: 1.0.3+2
  fl_chart:
    git:
      url: https://github.com/a-givertzman/fl_chart.git
      ref: 0.63.0+2
  cupertino_icons: ^1.0.2
  window_manager: ^0.3.0
  davi: ^3.3.0
  collection: ^1.18.0
  vector_math: ^2.1.4
  path_drawing: ^1.0.1
  scrollable_positioned_list: ^0.3.8
  markdown_widget: ^2.3.2+6
  flutter_svg: ^2.0.9
  flutter_math_fork: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  dart_code_metrics: ^5.1.0
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/img/
    - assets/settings/
    - assets/translations/
    - assets/unicodes/
    - assets/docs/
    - assets/image/
    - assets/image/program_sheets/ru/sheet03_mainScreen/
    - assets/image/program_sheets/ru/sheet04_shipinfo/
    - assets/image/program_sheets/ru/sheet05_loading/
    - assets/image/program_sheets/ru/sheet07_strength/
    - assets/image/program_sheets/ru/sheet08_stability/
    - assets/image/program_sheets/ru/sheet05_loading/tab01_ballast/
    - assets/image/program_sheets/ru/sheet05_loading/tab02_storeTanks/
    - assets/image/program_sheets/ru/sheet05_loading/tab03_stores/
    - assets/image/program_sheets/ru/sheet05_loading/tab04_bulkCargo/
    - assets/image/program_sheets/ru/sheet05_loading/tab06_containers/
    - assets/docs/user-guide/ru/
    - assets/docs/mock/
    - assets/reference/
    - assets/reference/RMRS/Rules/classification_&_construction_of_ships_&_offshore_installations/Ships_(primary_group)/Sea-Going_Ships/
    - assets/reference/RMRS/Rules/classification_&_construction_of_ships_&_offshore_installations/Ships_(primary_group)/Sea-Going_Ships/2-020101-174-1_clasification.pdf
    - assets/docs/user-guide/ru/part01_overview/
    - assets/docs/user-guide/ru/part02_operatingProcedure/
    - assets/docs/user-guide/ru/part03_mainScreen/
    - assets/docs/user-guide/ru/part04_shipInfo/
    - assets/docs/user-guide/ru/part05_loading/
    - assets/docs/user-guide/ru/part08_stability/
    - assets/docs/user-guide/ru/part06_draft/
    - assets/docs/user-guide/ru/part07_strength/
    - assets/docs/user-guide/ru/part01_overview/chapter01_programm/
    - assets/docs/user-guide/ru/part01_overview/chapter02_ship/
    - assets/docs/user-guide/ru/part05_loading/chapter01_ballast/
    - assets/docs/user-guide/ru/part05_loading/chapter02_storeTanks/
    - assets/docs/user-guide/ru/part05_loading/chapter03_stores/
    - assets/docs/user-guide/ru/part05_loading/chapter04_bulkCargo/
    - assets/docs/user-guide/ru/part05_loading/chapter05_unitCargo/
    - assets/docs/user-guide/ru/part05_loading/chapter06_containers/
    - assets/reference/IMO/internationalConvention/LL_66_88.pdf
    - assets/reference/OCX/gost_r_iso_10303-216-2023-1.pdf
    - assets/reference/RMRS/Guidelines/ships_&_offshore_installations/2-030101-046_LL_66_88.pdf
    - assets/reference/RMRS/Rules/classification_&_construction_of_ships_&_offshore_installations/Ships_(primary_group)/Sea-Going_Ships/2-020101-174-1_clasification.pdf
    - assets/reference/RMRS/Rules/classification_&_construction_of_ships_&_offshore_installations/Ships_(primary_group)/Sea-Going_Ships/2-020101-174-4_stability.pdf
    - assets/reference/RMRS/Rules/classification_&_construction_of_ships_&_offshore_installations/Ships_(primary_group)/Sea-Going_Ships/2-020101-174-5_subdivision.pdf
    - assets/reference/RMRS/Rules/different_types_of_ships/2-020101-013-E.pdf
